package com.prodapt.m2m.core.PIP;

import com.prodapt.m2m.core.PIP.utils.Consequence;
import java.util.ArrayList;
rule "Multi Rule 1"
salience 1
when
	$consequence : Consequence();
	eval( true );
then
	ArrayList<Integer> apocIndices = (ArrayList<Integer>)$consequence.getConsequence();
	apocIndices.add(1);
	System.out.println("Multi Rule 1");
	System.out.println("consequence" +apocIndices);
end

rule "Multi Rule 5"
salience 5
when 
	$consequence : Consequence();
	eval( true );
then
	ArrayList<Integer> apocIndices = (ArrayList<Integer>)$consequence.getConsequence();
	apocIndices.add(5);
	System.out.println("Multi Rule 5");
	System.out.println("consequence" +apocIndices);
end

rule "Multi Rule 2"
salience 2
when 
	$consequence : Consequence();
	eval( true );
then
	ArrayList<Integer> apocIndices = (ArrayList<Integer>)$consequence.getConsequence();
	apocIndices.add(2);
	System.out.println("Multi Rule 2");
	System.out.println("consequence" +apocIndices);
end

rule "Multi Rule 4"
salience 4
when 
	$consequence : Consequence();
	eval( true );
then
	ArrayList<Integer> apocIndices = (ArrayList<Integer>)$consequence.getConsequence();
	apocIndices.add(4);
	System.out.println("Multi Rule 4");
	System.out.println("consequence" +apocIndices);
end

rule "Multi Rule 3"
salience 3
when
	$consequence : Consequence(); 
	eval( true );
then
	ArrayList<Integer> apocIndices = (ArrayList<Integer>)$consequence.getConsequence();
	apocIndices.add(2);
	System.out.println("Multi Rule 3");
	System.out.println("consequence" +apocIndices);
end

rule "Verdict"
salience 6
when 
	$consequence : Consequence();
	eval( true );
then
	ArrayList<Integer> apocIndices = new java.util.ArrayList<Integer>();
	$consequence.setConsequence(apocIndices);
	System.out.println("Verdict");
	System.out.println("consequence" +apocIndices);
end